# Generated by Django 5.1.4 on 2025-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
