# Generated by Django 5.1.5 on 2025-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_department_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
