# Generated by Django 5.1.5 on 2025-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteclassification',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
