# Generated by Django 5.1.5 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_alter_wasteclassification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteclassification',
            name='bin_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wasteclassification',
            name='product_type',
            field=models.CharField(default='Unknown Product Type', max_length=100),
        ),
        migrations.AlterField(
            model_name='wasteclassification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wasteclassification',
            name='image',
            field=models.ImageField(upload_to='waste_classifications/'),
        ),
        migrations.AlterField(
            model_name='wasteclassification',
            name='predicted_class',
            field=models.CharField(max_length=50),
        ),
    ]
