# Generated by Django 5.1.4 on 2025-01-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recycling_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
