# Generated by Django 5.1.4 on 2025-01-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_bin'),
        ('scanner', '0003_userscore'),
    ]

    operations = [
    ]
