# Generated by Django 5.1.4 on 2025-01-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
