# Generated by Django 5.1.4 on 2025-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_materials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recyclable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recycling_bin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
