# Generated by Django 5.1.4 on 2025-01-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_product_labels_product_packaging_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recyclable',
        ),
    ]
