# Generated by Django 5.1.4 on 2025-01-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_remove_product_recyclable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packagings_materials_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
